version: '3.7'

services:
  consul-server:
    container_name: consul-server
    image: hashicorp/consul:1.13.3
    restart: always
    volumes:
      - ./configs.d/server.json:/consul/config/server.json:ro
      - ./configs.d/grafana.json:/consul/config/grafana.json:ro
      - ./configs.d/prometheus.json:/consul/config/prometheus.json:ro
      - ./configs.d/node-exporter.json:/consul/config/node-exporter.json:ro
      - ./configs.d/victoria-metrics.json:/consul/config/victoria-metrics.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command:
      - "agent"

  consul-client:
    container_name: consul-client
    image: hashicorp/consul:1.13.3
    restart: always
    volumes:
      - ./configs.d/client.json:/consul/config/client.json:ro
    networks:
      - consul
    command:
      - "agent"

  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.2
    restart: always
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - consul
    ports:
      - "3000:3000"

  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics:v1.83.0
    restart: always
    volumes:
      - vmdata:/storage
    networks:
      - consul
    ports:
      - "2003:2003"
      - "2003:2003/udp"
      - "4242:4242"
      - "8089:8089"
      - "8089:8089/udp"
      - "8428:8428"
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.39.1
    restart: always
    depends_on:
      - victoriametrics
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - consul
    ports:
      - "9090:9090"
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.4.0
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - consul
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

volumes:
  vmdata: {}
  grafana: {}

networks:
  consul:
    driver: bridge
